/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import gerarArquivoTXT.GerarTxt;

import java.awt.Font;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;

import javax.swing.JOptionPane;

import pingar.Pingar;

/**
 *
 * @author Gustavo
 */
public class TelaInicial extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form TelaInicial
	 */
	public TelaInicial() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jCheckBox1 = new javax.swing.JCheckBox();
		jCheckBox2 = new javax.swing.JCheckBox();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jButton1.setText("Pingar");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jTextArea2.setColumns(20);
		jTextArea2.setRows(5);
		jScrollPane2.setViewportView(jTextArea2);

		jCheckBox1.setText("Barulho");

		jCheckBox2.setText("Repetir");

		jButton2.setText("Documentar");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		586,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		jScrollPane2))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(0,
																		0,
																		Short.MAX_VALUE)
																.addComponent(
																		jButton1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		110,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(75, 75,
																		75)
																.addComponent(
																		jButton2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		104,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(154,
																		154,
																		154)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jCheckBox2)
																				.addComponent(
																						jCheckBox1))))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														jScrollPane2,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														494, Short.MAX_VALUE)
												.addComponent(jScrollPane1))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														jButton1,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jCheckBox1)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jCheckBox2)
																.addGap(0,
																		0,
																		Short.MAX_VALUE))
												.addComponent(
														jButton2,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addContainerGap()));

		pack();
	}// </editor-fold>

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// Codigo do boatao pingar
		
		//setup do botao(colocar tamanho ,fonte , mensagem e bloquear os botoes)
		
		Font font = new Font("Verdana", Font.PLAIN, 16);
		TelaInicial.jTextArea1.setFont(font);
		TelaInicial.jTextArea1.setText("Processando...");
		TelaInicial.jButton1.setEnabled(false);
		TelaInicial.jButton2.setEnabled(false);
		
		//fim do setup
		
		//Procedimento para pingar gerando thread caso o botao de repetir esteja desligado
		
		if (TelaInicial.jCheckBox2.isSelected() == false) {
			java.awt.EventQueue.invokeLater(new Runnable() {
				public void run() {
					Pingar ping = new Pingar(TelaInicial.jCheckBox1
							.isSelected());
					TelaInicial.jTextArea1.setText(ping.getTexto());
					TelaInicial.jButton1.setEnabled(true);
					TelaInicial.jButton2.setEnabled(true);
					if (ping.getErroDePing()) {
						TelaInicial.jTextArea2.setText(TelaInicial.jTextArea2
								.getText()
								+ "Houve um erro as "
								+ Horas()
								+ "\n");
						if (ping.getfazerBarulho()) {
							Toolkit.getDefaultToolkit().beep();
						}
					}
				}
			});
		} else {
			//Procedimento para pingar gerando thread caso o botao de repetir esteja ligado
			TelaInicial.jTextArea1.setText("");
			int repetir = Integer.parseInt(JOptionPane
					.showInputDialog("Repetir quantas vezes?"));
			for (int i = 0; i < repetir; i++) {
				PingRepetido ping = new PingRepetido();
				ping.rodar();			
			}
			TelaInicial.jButton1.setEnabled(true);
			TelaInicial.jButton2.setEnabled(true);
		}

	}

	private static String Horas() {
		//Obter o Horario
		String data = "dd/MM/yyyy";
		String hora = "h:mm - a";
		String hora1;

		java.util.Date agora = new java.util.Date();
		;
		SimpleDateFormat formata = new SimpleDateFormat(data);
		formata = new SimpleDateFormat(hora);
		hora1 = formata.format(agora);
		return hora1;

	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// Criar o arquivo
		TelaInicial.jButton1.setEnabled(false);
		TelaInicial.jButton2.setEnabled(false);
		TelaInicial.jTextArea1.setText("Gerando...");
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				Pingar ping = new Pingar(TelaInicial.jCheckBox1.isSelected());
				GerarTxt gerador = new GerarTxt();
				gerador.GerarArquivoTxt(ping.getTexto());
				TelaInicial.jButton1.setEnabled(true);
				TelaInicial.jButton2.setEnabled(true);
				TelaInicial.jTextArea1.setText("Gerado Relatorio");
				if (ping.getErroDePing()) {
					Toolkit.getDefaultToolkit().beep();
				}
			}
		});
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public void Gerarelainicio() {

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new TelaInicial().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private static javax.swing.JButton jButton1;
	private static javax.swing.JButton jButton2;
	private static javax.swing.JCheckBox jCheckBox1;
	private static javax.swing.JCheckBox jCheckBox2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private static javax.swing.JTextArea jTextArea1;
	private static javax.swing.JTextArea jTextArea2;

	// End of variables declaration

	public class PingRepetido {
		//Ping sendo repetido
		//Onde occorre o erro <==================
		public void rodar() {
			Pingar ping = new Pingar(TelaInicial.jCheckBox1.isSelected());	
			TelaInicial.jTextArea1.setText(jTextArea1.getText() + "\n"
					+ ping.getTexto());
			if (ping.getErroDePing()) {
				TelaInicial.jTextArea2.setText(TelaInicial.jTextArea2.getText()
						+ "Houve um erro as " + Horas() + "\n");
				if (ping.getfazerBarulho()) {
					Toolkit.getDefaultToolkit().beep();
				}
			}
		}
	}
}
